# Generated by Django 5.1.5 on 2025-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
